"""Vault operations — write pages, regenerate folder indexes, lint, git, stats."""
from __future__ import annotations

import logging
import subprocess
from datetime import datetime
from pathlib import Path
from typing import Any

from . import index as _idx
from . import pages
from . import slots
from . import store
from .renderer import Renderer, depth_of, materialize_new_page

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# New page
# ---------------------------------------------------------------------------


def new_page(
    name: str,
    *,
    template: str,
    meta: dict[str, Any] | None = None,
    folder: str | Path | None = None,
    renderer: Renderer,
    vault_root: Path,
) -> Path:
    """Create a fresh page from a template. Returns the new page path.

    Page lives at ``<vault_root>/<folder>/<name>.html``. The folder is
    created if missing. The folder index is regenerated.
    """
    if folder is None:
        folder_path = vault_root
    elif isinstance(folder, Path):
        folder_path = folder
    else:
        folder_path = vault_root / folder
    folder_path.mkdir(parents=True, exist_ok=True)

    safe_name = name if name.endswith(store.PAGE_SUFFIX) else f"{name}{store.PAGE_SUFFIX}"
    page_path = folder_path / safe_name
    if page_path.exists():
        raise FileExistsError(f"page already exists: {page_path}")

    page_meta = dict(meta or {})
    page_meta.setdefault("title", Path(safe_name).stem.replace("-", " ").replace("_", " "))

    materialize_new_page(
        page_path, template=template, meta=page_meta,
        renderer=renderer, vault_root=vault_root,
    )

    _rebuild_chain_to_root(folder_path, renderer=renderer, vault_root=vault_root)
    db = store.index_db_path(store.state_dir(vault_root))
    _idx.update_page(page_path, vault_root, db)
    return page_path


_TAG_RE = __import__("re").compile(r"<[^>]+>")
_WS_RE = __import__("re").compile(r"\s+")


def _card_snippet(html_or_text: str, max_len: int = 180) -> str:
    """Make a short, plain-text snippet for use in a folder card.

    Strips all HTML, collapses whitespace, takes the first sentence (up to
    the first period/Chinese period/newline) capped at ``max_len`` chars.
    """
    if not html_or_text:
        return ""
    text = _TAG_RE.sub(" ", html_or_text)
    text = _WS_RE.sub(" ", text).strip()
    if not text:
        return ""
    for sep in ("\n", "。", ". ", "！", "? ", "? "):
        idx = text.find(sep)
        if 0 < idx < max_len:
            text = text[: idx + len(sep)]
            break
    if len(text) > max_len:
        text = text[: max_len].rstrip() + "…"
    return text.strip()


def _rebuild_chain_to_root(
    folder: Path, *, renderer: Renderer, vault_root: Path,
) -> None:
    """Rebuild folder index for ``folder`` and every ancestor up to (and
    including) ``vault_root``. Child lists change up the chain whenever a
    new subfolder is created.
    """
    folder = folder.resolve()
    root = vault_root.resolve()
    current = folder
    while True:
        rebuild_folder_index(current, renderer=renderer, vault_root=vault_root)
        if current == root:
            break
        if root not in current.parents:
            break
        current = current.parent


# ---------------------------------------------------------------------------
# Rerender (apply current template to an existing page, preserving slots)
# ---------------------------------------------------------------------------


def rerender_page(
    path: Path, *, renderer: Renderer, vault_root: Path,
) -> bool:
    """Re-render an existing page from its current template, keeping slots.

    Returns True if the page was re-rendered, False if it was skipped
    (no meta block, unknown template, or read error). Use this after
    editing templates to refresh existing pages' shells without losing
    body content.
    """
    try:
        html = path.read_text(encoding="utf-8")
    except OSError:
        return False
    meta = slots.read_meta(html)
    if not meta:
        return False
    template = str(meta.get("template") or "")
    if not template or renderer.find_template(template) is None:
        return False
    if template == "folder":
        # folder/README.html is regenerated by rebuild_folder_index.
        return False

    saved: dict[str, str] = {}
    for sid in slots.list_slots(html):
        val = slots.read_slot(html, sid)
        if val is not None:
            saved[sid] = val

    new_html = renderer.render_new_page(
        template, meta, depth=depth_of(path, vault_root),
    )
    for sid, val in saved.items():
        try:
            new_html = slots.write_slot(new_html, sid, val)
        except KeyError:
            continue  # slot no longer declared by template
    path.write_text(new_html, encoding="utf-8")
    return True


def rerender_all_pages(
    vault_root: Path, *, renderer: Renderer,
) -> int:
    """Re-render every harness-managed content page. Returns count."""
    n = 0
    for p in pages.iter_pages(vault_root):
        try:
            if rerender_page(p, renderer=renderer, vault_root=vault_root):
                n += 1
        except Exception as e:
            logger.warning("rerender failed for %s: %s", p, e)
    return n


# ---------------------------------------------------------------------------
# Folder index regeneration
# ---------------------------------------------------------------------------


def rebuild_folder_index(
    folder: Path,
    *,
    renderer: Renderer,
    vault_root: Path,
) -> Path:
    """Regenerate ``<folder>/README.html`` from the folder's current contents.

    Preserves any slot content (notably ``description``) already written into
    the previous README — only the auto-managed parts (child list, updated
    stamp) are refreshed.

    For subfolder cards, the ``note`` shown is taken from the child folder
    README's ``description`` slot when present, falling back to ``meta.description``.
    """
    folder = folder.resolve()
    children: list[dict[str, Any]] = []

    for entry in sorted(folder.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower())):
        if entry.name.startswith("."):
            continue
        if entry.is_dir():
            sub_readme = entry / store.FOLDER_INDEX
            sub_meta: dict[str, Any] = {}
            sub_desc = ""
            if sub_readme.exists():
                try:
                    sub_meta = slots.read_meta_file(sub_readme)
                    sub_desc = (slots.read_slot_file(sub_readme, "description") or "").strip()
                except Exception:
                    pass
            note = _card_snippet(sub_desc or sub_meta.get("description") or "")
            # Count direct content pages + subfolders so the card can show
            # "5 pages · 2 folders" at a glance.
            n_pages = 0
            n_subfolders = 0
            try:
                for sub in entry.iterdir():
                    if sub.name.startswith(".") or sub.name.startswith("_"):
                        continue
                    if sub.is_dir():
                        n_subfolders += 1
                    elif sub.suffix == store.PAGE_SUFFIX and sub.name != store.FOLDER_INDEX:
                        n_pages += 1
            except OSError:
                pass
            children.append({
                "kind": "folder",
                "title": sub_meta.get("title") or entry.name,
                "href": f"{entry.name}/{store.FOLDER_INDEX}",
                "note": note,
                "n_pages": n_pages,
                "n_subfolders": n_subfolders,
            })
        elif entry.suffix == store.PAGE_SUFFIX and entry.name != store.FOLDER_INDEX:
            try:
                meta = slots.read_meta_file(entry)
            except Exception:
                meta = {}
            children.append({
                "kind": "page",
                "title": meta.get("title") or entry.stem,
                "href": entry.name,
                "template": meta.get("template") or "",
                "updated": meta.get("updated") or "",
            })

    # Surface a visible warning when the folder has too many direct content
    # pages — a clear signal that it should be split into subfolders. The
    # threshold (10) matches the human "more than 10 files = unstructured
    # dumping" heuristic.
    direct_page_count = sum(1 for c in children if c.get("kind") == "page")
    crowded_warning = direct_page_count > 10

    readme = folder / store.FOLDER_INDEX
    folder_meta: dict[str, Any] = {}
    preserved_slots: dict[str, str] = {}
    if readme.exists():
        try:
            old_html = readme.read_text(encoding="utf-8")
            folder_meta = slots.read_meta(old_html)
            for sid in slots.list_slots(old_html):
                val = slots.read_slot(old_html, sid)
                if val and val.strip():
                    preserved_slots[sid] = val
        except Exception:
            pass
    folder_meta.setdefault("title", folder.name if folder != vault_root else "wiki")

    html = renderer.render_folder_index(
        folder_meta, children, depth=depth_of(readme, vault_root),
        crowded_warning=crowded_warning,
        direct_page_count=direct_page_count,
    )
    for sid, content in preserved_slots.items():
        try:
            html = slots.write_slot(html, sid, content)
        except KeyError:
            # Slot no longer declared by the template; drop it.
            continue

    readme.write_text(html, encoding="utf-8")

    # Also write a plain-text README.md sibling so GitHub / IDE folder
    # browsers auto-render the index in markdown view.
    try:
        md_path = readme.with_suffix(".md")
        md_path.write_text(
            _render_folder_index_md(folder_meta, children, vault_root, folder),
            encoding="utf-8",
        )
    except Exception as e:
        logger.warning("README.md sibling write failed for %s: %s", folder, e)

    return readme


def _render_folder_index_md(
    meta: dict[str, Any],
    children: list[dict[str, Any]],
    vault_root: Path,
    folder: Path,
) -> str:
    """Plain-text markdown projection of a folder index.

    GitHub auto-renders ``README.md`` when viewing a folder, so this gives
    visitors the same navigation in plain markdown.
    """
    out: list[str] = []
    title = str(meta.get("title") or folder.name or "Index")
    out.append(f"# {title}")
    out.append("")

    desc = _card_snippet(meta.get("description") or "", max_len=400)
    if desc:
        out.append(desc)
        out.append("")

    folders = [c for c in children if c.get("kind") == "folder"]
    pages_ = [c for c in children if c.get("kind") == "page"]

    from urllib.parse import quote
    if folders:
        out.append("## Subfolders")
        out.append("")
        for c in folders:
            href = c["href"].rsplit("/", 1)[0] + "/"
            line = f"- [**{c['title']}**]({quote(href, safe='/')})"
            if c.get("note"):
                line += f" — {c['note']}"
            out.append(line)
        out.append("")

    if pages_:
        out.append("## Pages")
        out.append("")
        out.append("| Title | Template | Updated |")
        out.append("|---|---|---|")
        for c in pages_:
            tmpl = c.get("template") or ""
            upd = c.get("updated") or ""
            out.append(f"| [{c['title']}]({quote(c['href'], safe='/')}) | `{tmpl}` | {upd} |")
        out.append("")

    if not folders and not pages_:
        out.append("_(empty folder)_")
        out.append("")

    out.append("---")
    out.append("")
    out.append(
        f"_This file is auto-generated. The richly rendered version is "
        f"[`README.html`](./README.html); the human-edited description lives "
        f"in its `description` slot._"
    )
    return "\n".join(out)


def rebuild_all_folder_indexes(
    vault_root: Path, *, renderer: Renderer,
) -> int:
    """Regenerate every folder index. Returns count rebuilt."""
    n = 0
    rebuild_folder_index(vault_root, renderer=renderer, vault_root=vault_root)
    n += 1
    for sub in vault_root.rglob("*"):
        if not sub.is_dir():
            continue
        rel = sub.relative_to(vault_root)
        if any(part in store.SKIP_DIRS or part.startswith(".") for part in rel.parts):
            continue
        rebuild_folder_index(sub, renderer=renderer, vault_root=vault_root)
        n += 1
    return n


# ---------------------------------------------------------------------------
# Lint
# ---------------------------------------------------------------------------


#: Folder is flagged for split when it has more direct content pages than this.
FOLDER_SPLIT_THRESHOLD = 7


def lint(vault_root: Path, *, renderer: Renderer) -> str:
    """Report page-level issues + folder housekeeping signals.

    Folder housekeeping checks flag conditions that should trigger an agent
    tidy pass: folders too large to grok at a glance, folders whose README
    has no human-written description, and folders that are empty.
    """
    pages_list = list(pages.iter_pages(vault_root))
    if not pages_list:
        return "# Wiki lint report\n\n(empty vault — nothing to lint)"

    known_templates = set(renderer.template_names())
    template_slots = {t.name: set(t.slots) for t in renderer.list_templates()}

    missing_meta: list[str] = []
    unknown_template: list[tuple[str, str]] = []
    bad_slots: list[tuple[str, str]] = []
    broken_links: list[tuple[str, str]] = []
    empty_pages: list[str] = []

    for p in pages_list:
        rel = str(p.relative_to(vault_root))
        try:
            html = p.read_text(encoding="utf-8")
        except OSError:
            continue
        meta = slots.read_meta(html)
        if not meta:
            missing_meta.append(rel)
            continue

        tmpl = meta.get("template")
        if not tmpl or tmpl not in known_templates:
            unknown_template.append((rel, str(tmpl or "<missing>")))
            continue

        declared = template_slots.get(str(tmpl), set())
        actual = set(slots.list_slots(html))
        unexpected = actual - declared
        for s in unexpected:
            bad_slots.append((rel, s))

        if not slots.slot_text(html).strip():
            empty_pages.append(rel)

        for href in _extract_hrefs(html):
            target = _resolve_href(p, href, vault_root)
            if target is None:
                continue
            if not target.exists():
                broken_links.append((rel, href))

    # ── Reachability check ───────────────────────────────────────────
    # A page is "buried" if the only inbound reference is the auto-
    # generated PAGES list in its own folder's README (i.e. nobody
    # writes about it anywhere). Such pages are reachable only by
    # someone who already knows the folder structure — they have no
    # contextual entry point. Rule: every page must be referenced from
    # (a) its parent folder README's description slot, OR (b) an
    # ancestor folder's README description slot, OR (c) some other
    # content page's body/slots. Auto page-list doesn't count.
    meaningful_inbound: dict[Path, list[str]] = {p.resolve(): [] for p in pages_list}

    # Sources of outbound hrefs to consider: content pages (their full
    # body) PLUS folder READMEs (only their slot content — not the
    # auto-generated PAGES list, which is template chrome, not an
    # intentional reference).
    href_sources: list[tuple[Path, str]] = []
    for p in pages_list:
        try:
            href_sources.append((p, p.read_text(encoding="utf-8")))
        except OSError:
            continue
    for folder in _iter_folders(vault_root):
        readme = folder / store.FOLDER_INDEX
        if not readme.exists():
            continue
        try:
            html = readme.read_text(encoding="utf-8")
        except OSError:
            continue
        slot_text = "\n".join(
            slots.read_slot(html, sid) or "" for sid in slots.list_slots(html)
        )
        href_sources.append((readme, slot_text))

    for src_path, scan_text in href_sources:
        rel_src = str(src_path.relative_to(vault_root))
        for href in _extract_hrefs(scan_text):
            target = _resolve_href(src_path, href, vault_root)
            if target is None:
                continue
            target = target.resolve()
            if target == src_path.resolve():
                continue  # self-link
            if target in meaningful_inbound:
                meaningful_inbound[target].append(rel_src)

    buried: list[str] = []
    for p in pages_list:
        if not meaningful_inbound[p.resolve()]:
            buried.append(str(p.relative_to(vault_root)))

    # ── Folder housekeeping ───────────────────────────────────────────
    crowded: list[tuple[str, int]] = []
    missing_description: list[str] = []
    empty_folders: list[str] = []
    missing_readme: list[str] = []

    for folder in _iter_folders(vault_root):
        rel_folder = "(root)" if folder == vault_root else str(folder.relative_to(vault_root))
        direct_pages = [
            e for e in folder.iterdir()
            if e.suffix == store.PAGE_SUFFIX and e.name != store.FOLDER_INDEX
        ]
        direct_subfolders = [
            e for e in folder.iterdir()
            if e.is_dir() and not e.name.startswith(".")
        ]
        if len(direct_pages) > FOLDER_SPLIT_THRESHOLD:
            crowded.append((rel_folder, len(direct_pages)))
        if not direct_pages and not direct_subfolders:
            empty_folders.append(rel_folder)

        readme = folder / store.FOLDER_INDEX
        if not readme.exists():
            missing_readme.append(rel_folder)
            continue
        try:
            desc = (slots.read_slot_file(readme, "description") or "").strip()
        except Exception:
            desc = ""
        if not desc:
            missing_description.append(rel_folder)

    out: list[str] = [
        "# Wiki lint report",
        "",
        f"Pages:                              {len(pages_list)}",
        f"Missing meta block:                 {len(missing_meta)}",
        f"Unknown template:                   {len(unknown_template)}",
        f"Slots not declared by template:     {len(bad_slots)}",
        f"Pages with no slot content:         {len(empty_pages)}",
        f"Broken local <a href> links:        {len(broken_links)}",
        f"Folders missing README.html:        {len(missing_readme)}",
        f"Folders without description slot:   {len(missing_description)}",
        f"Folders with >{FOLDER_SPLIT_THRESHOLD} direct pages (split?):  {len(crowded)}",
        f"Empty folders:                      {len(empty_folders)}",
        f"Buried pages (no inbound ref):      {len(buried)}",
        "",
    ]

    def _section(title: str, rows: list[str]) -> None:
        if not rows:
            return
        out.append(f"## {title}")
        out.extend(f"- {r}" for r in rows[:30])
        if len(rows) > 30:
            out.append(f"- ... and {len(rows) - 30} more")
        out.append("")

    _section("Missing meta", missing_meta)
    _section("Unknown template",
             [f"`{p}` → `{t}`" for p, t in unknown_template])
    _section("Unexpected slots",
             [f"`{p}` → slot `{s}`" for p, s in bad_slots])
    _section("Empty pages", empty_pages)
    _section("Broken links",
             [f"`{p}` → `{h}`" for p, h in broken_links])
    _section("Folders missing README.html", missing_readme)
    _section("Folders without description slot", missing_description)
    _section("Crowded folders (consider splitting)",
             [f"`{f}` — {n} direct pages" for f, n in crowded])
    _section("Empty folders", empty_folders)
    _section(
        "Buried pages — link them from an ancestor README description, "
        "feature in a callout, OR move to where they're actually used. "
        "Being auto-listed in the parent's PAGES section doesn't count: "
        "the reader has to drill in blind to find them.",
        buried,
    )

    return "\n".join(out).rstrip()


def _iter_folders(vault_root: Path):
    yield vault_root
    for p in sorted(vault_root.rglob("*")):
        if not p.is_dir():
            continue
        rel = p.relative_to(vault_root)
        if any(part in store.SKIP_DIRS or part.startswith(".") for part in rel.parts):
            continue
        yield p


_SCRIPT_RE = __import__("re").compile(r"<script\b[^>]*>.*?</script>", __import__("re").DOTALL | __import__("re").IGNORECASE)
_STYLE_RE = __import__("re").compile(r"<style\b[^>]*>.*?</style>", __import__("re").DOTALL | __import__("re").IGNORECASE)
_HREF_RE = __import__("re").compile(r'<a\b[^>]*\shref="([^"]+)"', __import__("re").IGNORECASE)


def _extract_hrefs(html: str) -> list[str]:
    # Strip <script> and <style> so we don't catch JS-template hrefs.
    body = _SCRIPT_RE.sub("", html)
    body = _STYLE_RE.sub("", body)
    return [m.group(1) for m in _HREF_RE.finditer(body)]


def _resolve_href(page_path: Path, href: str, vault_root: Path) -> Path | None:
    """Resolve a local href relative to ``page_path``. Returns None for external."""
    if href.startswith(("http://", "https://", "mailto:", "#", "javascript:")):
        return None
    href_clean = href.split("#", 1)[0].split("?", 1)[0]
    if not href_clean:
        return None
    target = (page_path.parent / href_clean).resolve()
    try:
        target.relative_to(vault_root.resolve())
    except ValueError:
        return None
    return target


# ---------------------------------------------------------------------------
# Git
# ---------------------------------------------------------------------------


def git_commit(message: str, *, vault_root: Path) -> dict[str, Any]:
    if not (vault_root / ".git").exists():
        return {"ok": False, "error": "vault is not a git repo"}
    try:
        subprocess.run(
            ["git", "-C", str(vault_root), "add", "-A"],
            check=True, capture_output=True, timeout=15,
        )
        status = subprocess.run(
            ["git", "-C", str(vault_root), "status", "--porcelain"],
            check=True, capture_output=True, timeout=15, text=True,
        ).stdout.strip()
        if not status:
            return {"ok": True, "committed": False}
        subprocess.run(
            ["git", "-C", str(vault_root), "commit", "-m", message,
             "--author", "WikiAgentHarness <memory@wiki-agent.local>"],
            check=True, capture_output=True, timeout=15,
        )
        h = subprocess.run(
            ["git", "-C", str(vault_root), "rev-parse", "--short", "HEAD"],
            check=True, capture_output=True, timeout=15, text=True,
        ).stdout.strip()
    except subprocess.CalledProcessError as e:
        return {"ok": False, "error": (e.stderr or b"").decode() or str(e)}
    except Exception as e:
        return {"ok": False, "error": str(e)}
    return {"ok": True, "committed": True, "hash": h}


def git_touched_pages(vault_root: Path) -> tuple[list[Path], list[Path]]:
    """Return (all_touched, newly_created) content pages since last commit."""
    if not (vault_root / ".git").exists():
        return [], []
    try:
        out = subprocess.run(
            ["git", "-C", str(vault_root), "status", "--porcelain"],
            check=True, capture_output=True, timeout=15, text=True,
        ).stdout
    except Exception:
        return [], []
    touched: list[Path] = []
    created: list[Path] = []
    for line in out.splitlines():
        if len(line) < 4:
            continue
        st = line[:2]
        rel = line[3:].strip().strip('"')
        if " -> " in rel:
            rel = rel.split(" -> ", 1)[1]
        if not rel.endswith(store.PAGE_SUFFIX):
            continue
        p = vault_root / rel
        if p.name == store.FOLDER_INDEX:
            continue
        if not p.exists():
            continue
        touched.append(p)
        if st.strip() == "??":
            created.append(p)
    return touched, created


# ---------------------------------------------------------------------------
# Stats
# ---------------------------------------------------------------------------


def stats(vault_root: Path) -> dict[str, Any]:
    by_template: dict[str, int] = {}
    n = 0
    for p in pages.iter_pages(vault_root):
        try:
            meta = slots.read_meta_file(p)
        except Exception:
            continue
        t = str(meta.get("template") or "?")
        by_template[t] = by_template.get(t, 0) + 1
        n += 1

    db = store.index_db_path(store.state_dir(vault_root))
    try:
        idx = _idx.stats(db)
    except Exception:
        idx = {}

    return {
        "pages": n,
        "by_template": by_template,
        "fts_rows": idx.get("pages", 0),
        "last_reindex": idx.get("last_reindex"),
        "vault_root": str(vault_root),
    }
